FROM ewolff/docker-java
ADD ~/workspace/Turbine/Lego_ms_turbine-Build/microservice-demo/microservice-demo-turbine-server/target/microservice-demo-turbine-server-0.0.1-SNAPSHOT.jar .
CMD /usr/bin/java -Xmx400m -Xms400m -jar microservice-demo-turbine-server-0.0.1-SNAPSHOT.jar
EXPOSE 8989
