FROM ewolff/docker-java
ADD ~/workspace/Zuul/../../../target/microservice-demo-zuul-server-0.0.1-SNAPSHOT.jar .
CMD /usr/bin/java -Xmx400m -Xms400m -jar microservice-demo-zuul-server-0.0.1-SNAPSHOT.jar
EXPOSE 8080
