FROM ewolff/docker-java
ADD ~/workspace/Zuul/Lego_ms_zuul-Build/microservice-demo/microservice-demo-zuul-server/target/microservice-demo-zuul-server-0.0.1-SNAPSHOT.jar .
CMD /usr/bin/java -Xmx400m -Xms400m -jar microservice-demo-zuul-server-0.0.1-SNAPSHOT.jar
EXPOSE 8080
