FROM ewolff/docker-java
ADD ~/workspace/Order/Lego_ms_order-Build/microservice-demo/microservice-demo-order/target/microservice-demo-order-0.0.1-SNAPSHOT.jar .
CMD /usr/bin/java -Xmx400m -Xms400m -jar microservice-demo-order-0.0.1-SNAPSHOT.jar 
EXPOSE 8080
