FROM ewolff/docker-java
ADD ~/workspace/Catalog/Lego_ms_catalog-Build/microservice-demo/microservice-demo-catalog/target/microservice-demo-catalog-0.0.1-SNAPSHOT.jar .
CMD /usr/bin/java -Xmx400m -Xms400m -jar microservice-demo-catalog-0.0.1-SNAPSHOT.jar
EXPOSE 8080
