FROM ewolff/docker-java
ADD ~/workspace/Customer/Lego_ms_customer-Build/microservice-demo/microservice-demo-customer/target/microservice-demo-customer-0.0.1-SNAPSHOT.jar .
CMD /usr/bin/java -Xmx400m -Xms400m -jar microservice-demo-customer-0.0.1-SNAPSHOT.jar
EXPOSE 8080
